// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class Options {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    registry.Add(global::Options.ServerTarget);
    registry.Add(global::Options.MessageId);
  }
  #endregion
  #region Extensions
  public const int ServerTargetFieldNumber = 51234;
  public static pb::GeneratedExtensionBase<string> ServerTarget;
  public const int MessageIdFieldNumber = 51235;
  public static pb::GeneratedExtensionBase<int> MessageId;
  #endregion
  
  #region Static variables
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static Options() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1vcHRpb25zLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5w", 
          "cm90bzpFCgxzZXJ2ZXJUYXJnZXQSHy5nb29nbGUucHJvdG9idWYuTWVzc2Fn", 
          "ZU9wdGlvbnMYopADIAEoCVIMc2VydmVyVGFyZ2V0Oj8KCW1lc3NhZ2VJZBIf", 
          "Lmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxijkAMgASgFUgltZXNz", 
        "YWdlSWRiBnByb3RvMw=="));
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      global::Options.ServerTarget = pb::GeneratedSingleExtension<string>.CreateInstance(global::Options.Descriptor.Extensions[0]);
      global::Options.MessageId = pb::GeneratedSingleExtension<int>.CreateInstance(global::Options.Descriptor.Extensions[1]);
      pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
      RegisterAllExtensions(registry);
      global::Google.ProtocolBuffers.DescriptorProtos.DescriptorProtoFile.RegisterAllExtensions(registry);
      return registry;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        global::Google.ProtocolBuffers.DescriptorProtos.DescriptorProtoFile.Descriptor, 
        }, assigner);
  }
  #endregion
  
}

#endregion Designer generated code
