//code generated by generator don't edit.

namespace Google.Protobuf.Reflection
{
	internal static class MessageAOTInjector
	{
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<DescriptorProto.Types.ExtensionRange, int> _internel1;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<FileDescriptorProto, FieldDescriptorProto.Types.Label> _internel2;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<FieldDescriptorProto, FieldDescriptorProto.Types.Type> _internel3;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<MethodDescriptorProto, bool> _internel4;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<FileOptions, FileOptions.Types.OptimizeMode> _internel5;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<FieldOptions, FieldOptions.Types.CType> _internel6;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<FieldOptions, FieldOptions.Types.JSType> _internel7;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<MethodOptions, MethodOptions.Types.IdempotencyLevel> _internel8;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<UninterpretedOption, ulong> _internel9;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<UninterpretedOption, long> _internel10;
        internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<UninterpretedOption, double> _internel11;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<SCloginResponse,float> _SCloginResponse_float;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<SCPlayerInfoResponse,float> _SCPlayerInfoResponse_float;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<CSSkillEmitRequest,InOrOutScene> _CSSkillEmitRequest_InOrOutScene;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<MarketItemMsg,CostType> _MarketItemMsg_CostType;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<MarketRequest,Category> _MarketRequest_Category;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<MarketResponse,Category> _MarketResponse_Category;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<LottoRequest,CostType> _LottoRequest_CostType;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<LottoResponse,CostType> _LottoResponse_CostType;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<CSFriendRequest,FriendReqType> _CSFriendRequest_FriendReqType;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<SCFriendResponse,FriendReqType> _SCFriendResponse_FriendReqType;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<CSFBLoginRequest,OsType> _CSFBLoginRequest_OsType;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<CSPlayerFeedbackRequest,FeedbackType> _CSPlayerFeedbackRequest_FeedbackType;
		internal static Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper<CSClientLogRequest,float> _CSClientLogRequest_float;
	}
}
