//code generated by generator don't edit.
using Google.Protobuf;

namespace EngineCore
{
	public static class MessageTargetDefine
	{
		public const string GmAddAttr= "gm/addattr";
		public const string GmAddProp= "gm/addprop";
		public const string GmFinishTask= "gm/finishtask";
		public const string GmOfficer= "gm/officer";
		public const string GMGetPlayerMessageRequest= "gm/gmPlayerInfo";
		public const string CSEnterRequest= "jigsaw/enter";
		public const string CSQuitRequest= "jigsaw/quit";
		public const string CSSuspendRequest= "jigsaw/suspend";
		public const string CSResumeRequest= "jigsaw/resume";
		public const string CSStartRequest= "jigsaw/start";
		public const string CSFinishRequest= "jigsaw/finish";
		public const string CSRegRequest= "auth/reg";
		public const string CSAuthRequest= "auth/auth";
		public const string CSloginRequest= "login/login";
		public const string CSChapterListRequest= "chapter/list";
		public const string CSChapterDetailRequest= "chapter/detail";
		public const string CSClearChapterRedRequest= "chapter/clearRed";
		public const string CSSceneEnterRequest= "scene/enter";
		public const string CSSceneRewardRequest= "scene/reward";
		public const string CSSceneQuitRequest= "scene/quit";
		public const string CSSceneSuspendRequest= "scene/suspend";
		public const string CSSceneResumeRequest= "scene/resume";
		public const string CSSceneStartRequest= "scene/start";
		public const string CSSearchSceneSelectOfficerReq= "scene/selectofficer";
		public const string CSBuyItemRequest= "item/buy";
		public const string CSPlayerPropRequest= "player/prop/list";
		public const string CSPlayerPropRecentRequest= "player/prop/recent/empty";
		public const string CSPlayerInfoRequest= "player/info/info";
		public const string CSRenameRequest= "player/info/rename";
		public const string CSOfficerListRequest= "officer/list";
		public const string CSOfficerInfoRequest= "officer/info";
		public const string CSEventPhaseFeedbackRequest= "officer/event/phase/feedback";
		public const string CSEventRewardRequest= "officer/event/reward";
		public const string CSOfficerCombineRequest= "officer/combine";
		public const string CSOfficerUpdateRequest= "officer/update";
		public const string CSEventEnterRequest= "officer/event/enter";
		public const string CSEventDropInfoRequest= "officer/event/dropInfo";
		public const string CSSkillEmitRequest= "skill/emit";
		public const string CSSkillTimerEmitReq= "skill/emit/timer";
		public const string CSReasoningRewardReq= "officer/reasoning/reward";
		public const string CSFindEnterReq= "officer/find/enter";
		public const string CSFindRewardReq= "officer/find/reward";
		public const string CSSkyEyeRewardReq= "officer/skyEye/reward";
		public const string CSSkyEyeReq= "officer/skyEye/list";
		public const string MarketRequest= "player/market/list";
		public const string MarkeBuyRequest= "player/market/buy";
		public const string CSMarketItemRequest= "player/market/item";
		public const string MarkeFreshRequest= "player/market/black/fresh";
		public const string CSNoticeListRequest= "notice/list";
		public const string CSPingRequest= "ping/ping";
		public const string CSMessageRequest= "ping/message";
		public const string LottoRequest= "player/lotto/get";
		public const string LottoBuyRequest= "player/lotto/buy";
		public const string CSGooglePayChargeRequest= "player/charge/google";
		public const string CSIOSPayChargeRequest= "player/charge/ios";
		public const string CSTaskListRequest= "task/list";
		public const string CSTaskCommitRequest= "task/commit";
		public const string CSTriggerTaskActiveRequest= "task/trigger";
		public const string CSTaskIdListRequest= "task/idList";
		public const string CSAchievementRequest= "/player/achievement/list";
		public const string CSAchievementSubmitRequest= "/player/achievement/submit";
		public const string CSActivityBaseListRequest= "activity/base/list";
		public const string CSActivityRequest= "activity/base/quest";
		public const string CSActivityRewardRequest= "activity/reward";
		public const string CSCartoonEnterRequest= "cartoon/enter";
		public const string CSCartoonRewardRequest= "cartoon/reward";
		public const string CSCartoonQuitRequest= "cartoon/quit";
		public const string CSEmailListRequest= "email/list";
		public const string CSEmailRewardRequest= "email/reward";
		public const string CSEmailReadRequest= "email/read";
		public const string CSTitleRequest= "/player/title/list";
		public const string CSTitleActiveRequest= "/player/title/active";
		public const string CSTitleGetRequest= "/player/title/get";
		public const string CSFriendRequest= "player/friend/list";
		public const string CSFriendAddRequest= "player/friend/add";
		public const string CSFriendDelRequest= "player/friend/del";
		public const string CSFriendAgreeRequest= "player/friend/agree";
		public const string CSFriendDelApplyRequest= "player/friend/delApply";
		public const string CSFriendGiftRequest= "player/friend/gift/list";
		public const string CSFriendGiftSendRequest= "player/friend/gift/send";
		public const string CSFriendGiftDrawRequest= "player/friend/gift/draw";
		public const string CSFriendViewRequest= "player/friend/view";
		public const string CSFriendSwitchRequest= "player/friend/switch";
		public const string CSFriendRecommendListRequest= "player/friend/recommend/list";
		public const string CSFriendRecommendGetRequest= "player/friend/recommend/get";
		public const string CSFriendRecommendApplyRequest= "player/friend/recommend/apply";
		public const string CSBuildingListReq= "building/list";
		public const string CSBuildingUnlockReq= "building/unlock";
		public const string CSCanTaskRequest= "task/canTask";
		public const string CSRegGuestRequest= "auth/guest/reg";
		public const string CSIdentifyCheckRequest= "auth/identify/check";
		public const string CSFBLoginRequest= "auth/fb/login";
		public const string CSFBBindRequest= "auth/fb/bind";
		public const string PlayerPropSellRequest= "player/prop/sell";
		public const string CSDropReq= "player/prop/drop";
		public const string CSChatFinishRequest= "player/chat/finish";
		public const string CSGetAllRewardedTasksRequest= "task/getAllRewardedTasks";
		public const string CSPlayerCheckInInfoReq= "checkin/info";
		public const string CSPlayerCheckInReq= "checkin/checkin";
		public const string CSPlayerRenewIconReq= "player/info/renewicon";
		public const string CSPlayerGuildRequest= "player/info/guild";
		public const string CSPlayerGuildUpdateRequest= "player/info/guildUpdate";
		public const string CSPlayerFeedbackRequest= "player/feedback/submit";
		public const string CSSceneReconnectRequest= "scene/reconnect";
		public const string CSSceneDifficultyReq= "scene/getDifficulty";
		public const string CSJigsawReconnectRequest= "jigsaw/reconnect";
		public const string CSGetServiceConfigRequest= "sys/getServiceConfig";
		public const string CSGetServiceConfigSingleRequest= "sys/getSingleServiceConfig";
		public const string CSGetPathConfigRequest= "sys/path";
		public const string CSClientLogRequest= "sys/clientLog";
		public const string CSGetPushRequest= "push/getPush";
		public const string CSBuyPushRequest= "push/buyPush";
		public const string CSCombineInfoRequest= "combine/list";
		public const string CSCombineRequest= "combine/do";

		public static string GetServerUrl(IMessage message)
		{
			string serverUrl = string.Empty;
			string messageDescriptorName = message.Descriptor.Name;

			switch(messageDescriptorName)
			{
				case "GmAddAttr":
					serverUrl = "gm/addattr";
					break;
				case "GmAddProp":
					serverUrl = "gm/addprop";
					break;
				case "GmFinishTask":
					serverUrl = "gm/finishtask";
					break;
				case "GmOfficer":
					serverUrl = "gm/officer";
					break;
				case "GMGetPlayerMessageRequest":
					serverUrl = "gm/gmPlayerInfo";
					break;
				case "CSEnterRequest":
					serverUrl = "jigsaw/enter";
					break;
				case "CSQuitRequest":
					serverUrl = "jigsaw/quit";
					break;
				case "CSSuspendRequest":
					serverUrl = "jigsaw/suspend";
					break;
				case "CSResumeRequest":
					serverUrl = "jigsaw/resume";
					break;
				case "CSStartRequest":
					serverUrl = "jigsaw/start";
					break;
				case "CSFinishRequest":
					serverUrl = "jigsaw/finish";
					break;
				case "CSRegRequest":
					serverUrl = "auth/reg";
					break;
				case "CSAuthRequest":
					serverUrl = "auth/auth";
					break;
				case "CSloginRequest":
					serverUrl = "login/login";
					break;
				case "CSChapterListRequest":
					serverUrl = "chapter/list";
					break;
				case "CSChapterDetailRequest":
					serverUrl = "chapter/detail";
					break;
				case "CSClearChapterRedRequest":
					serverUrl = "chapter/clearRed";
					break;
				case "CSSceneEnterRequest":
					serverUrl = "scene/enter";
					break;
				case "CSSceneRewardRequest":
					serverUrl = "scene/reward";
					break;
				case "CSSceneQuitRequest":
					serverUrl = "scene/quit";
					break;
				case "CSSceneSuspendRequest":
					serverUrl = "scene/suspend";
					break;
				case "CSSceneResumeRequest":
					serverUrl = "scene/resume";
					break;
				case "CSSceneStartRequest":
					serverUrl = "scene/start";
					break;
				case "CSSearchSceneSelectOfficerReq":
					serverUrl = "scene/selectofficer";
					break;
				case "CSBuyItemRequest":
					serverUrl = "item/buy";
					break;
				case "CSPlayerPropRequest":
					serverUrl = "player/prop/list";
					break;
				case "CSPlayerPropRecentRequest":
					serverUrl = "player/prop/recent/empty";
					break;
				case "CSPlayerInfoRequest":
					serverUrl = "player/info/info";
					break;
				case "CSRenameRequest":
					serverUrl = "player/info/rename";
					break;
				case "CSOfficerListRequest":
					serverUrl = "officer/list";
					break;
				case "CSOfficerInfoRequest":
					serverUrl = "officer/info";
					break;
				case "CSEventPhaseFeedbackRequest":
					serverUrl = "officer/event/phase/feedback";
					break;
				case "CSEventRewardRequest":
					serverUrl = "officer/event/reward";
					break;
				case "CSOfficerCombineRequest":
					serverUrl = "officer/combine";
					break;
				case "CSOfficerUpdateRequest":
					serverUrl = "officer/update";
					break;
				case "CSEventEnterRequest":
					serverUrl = "officer/event/enter";
					break;
				case "CSEventDropInfoRequest":
					serverUrl = "officer/event/dropInfo";
					break;
				case "CSSkillEmitRequest":
					serverUrl = "skill/emit";
					break;
				case "CSSkillTimerEmitReq":
					serverUrl = "skill/emit/timer";
					break;
				case "CSReasoningRewardReq":
					serverUrl = "officer/reasoning/reward";
					break;
				case "CSFindEnterReq":
					serverUrl = "officer/find/enter";
					break;
				case "CSFindRewardReq":
					serverUrl = "officer/find/reward";
					break;
				case "CSSkyEyeRewardReq":
					serverUrl = "officer/skyEye/reward";
					break;
				case "CSSkyEyeReq":
					serverUrl = "officer/skyEye/list";
					break;
				case "MarketRequest":
					serverUrl = "player/market/list";
					break;
				case "MarkeBuyRequest":
					serverUrl = "player/market/buy";
					break;
				case "CSMarketItemRequest":
					serverUrl = "player/market/item";
					break;
				case "MarkeFreshRequest":
					serverUrl = "player/market/black/fresh";
					break;
				case "CSNoticeListRequest":
					serverUrl = "notice/list";
					break;
				case "CSPingRequest":
					serverUrl = "ping/ping";
					break;
				case "CSMessageRequest":
					serverUrl = "ping/message";
					break;
				case "LottoRequest":
					serverUrl = "player/lotto/get";
					break;
				case "LottoBuyRequest":
					serverUrl = "player/lotto/buy";
					break;
				case "CSGooglePayChargeRequest":
					serverUrl = "player/charge/google";
					break;
				case "CSIOSPayChargeRequest":
					serverUrl = "player/charge/ios";
					break;
				case "CSTaskListRequest":
					serverUrl = "task/list";
					break;
				case "CSTaskCommitRequest":
					serverUrl = "task/commit";
					break;
				case "CSTriggerTaskActiveRequest":
					serverUrl = "task/trigger";
					break;
				case "CSTaskIdListRequest":
					serverUrl = "task/idList";
					break;
				case "CSAchievementRequest":
					serverUrl = "/player/achievement/list";
					break;
				case "CSAchievementSubmitRequest":
					serverUrl = "/player/achievement/submit";
					break;
				case "CSActivityBaseListRequest":
					serverUrl = "activity/base/list";
					break;
				case "CSActivityRequest":
					serverUrl = "activity/base/quest";
					break;
				case "CSActivityRewardRequest":
					serverUrl = "activity/reward";
					break;
				case "CSCartoonEnterRequest":
					serverUrl = "cartoon/enter";
					break;
				case "CSCartoonRewardRequest":
					serverUrl = "cartoon/reward";
					break;
				case "CSCartoonQuitRequest":
					serverUrl = "cartoon/quit";
					break;
				case "CSEmailListRequest":
					serverUrl = "email/list";
					break;
				case "CSEmailRewardRequest":
					serverUrl = "email/reward";
					break;
				case "CSEmailReadRequest":
					serverUrl = "email/read";
					break;
				case "CSTitleRequest":
					serverUrl = "/player/title/list";
					break;
				case "CSTitleActiveRequest":
					serverUrl = "/player/title/active";
					break;
				case "CSTitleGetRequest":
					serverUrl = "/player/title/get";
					break;
				case "CSFriendRequest":
					serverUrl = "player/friend/list";
					break;
				case "CSFriendAddRequest":
					serverUrl = "player/friend/add";
					break;
				case "CSFriendDelRequest":
					serverUrl = "player/friend/del";
					break;
				case "CSFriendAgreeRequest":
					serverUrl = "player/friend/agree";
					break;
				case "CSFriendDelApplyRequest":
					serverUrl = "player/friend/delApply";
					break;
				case "CSFriendGiftRequest":
					serverUrl = "player/friend/gift/list";
					break;
				case "CSFriendGiftSendRequest":
					serverUrl = "player/friend/gift/send";
					break;
				case "CSFriendGiftDrawRequest":
					serverUrl = "player/friend/gift/draw";
					break;
				case "CSFriendViewRequest":
					serverUrl = "player/friend/view";
					break;
				case "CSFriendSwitchRequest":
					serverUrl = "player/friend/switch";
					break;
				case "CSFriendRecommendListRequest":
					serverUrl = "player/friend/recommend/list";
					break;
				case "CSFriendRecommendGetRequest":
					serverUrl = "player/friend/recommend/get";
					break;
				case "CSFriendRecommendApplyRequest":
					serverUrl = "player/friend/recommend/apply";
					break;
				case "CSBuildingListReq":
					serverUrl = "building/list";
					break;
				case "CSBuildingUnlockReq":
					serverUrl = "building/unlock";
					break;
				case "CSCanTaskRequest":
					serverUrl = "task/canTask";
					break;
				case "CSRegGuestRequest":
					serverUrl = "auth/guest/reg";
					break;
				case "CSIdentifyCheckRequest":
					serverUrl = "auth/identify/check";
					break;
				case "CSFBLoginRequest":
					serverUrl = "auth/fb/login";
					break;
				case "CSFBBindRequest":
					serverUrl = "auth/fb/bind";
					break;
				case "PlayerPropSellRequest":
					serverUrl = "player/prop/sell";
					break;
				case "CSDropReq":
					serverUrl = "player/prop/drop";
					break;
				case "CSChatFinishRequest":
					serverUrl = "player/chat/finish";
					break;
				case "CSGetAllRewardedTasksRequest":
					serverUrl = "task/getAllRewardedTasks";
					break;
				case "CSPlayerCheckInInfoReq":
					serverUrl = "checkin/info";
					break;
				case "CSPlayerCheckInReq":
					serverUrl = "checkin/checkin";
					break;
				case "CSPlayerRenewIconReq":
					serverUrl = "player/info/renewicon";
					break;
				case "CSPlayerGuildRequest":
					serverUrl = "player/info/guild";
					break;
				case "CSPlayerGuildUpdateRequest":
					serverUrl = "player/info/guildUpdate";
					break;
				case "CSPlayerFeedbackRequest":
					serverUrl = "player/feedback/submit";
					break;
				case "CSSceneReconnectRequest":
					serverUrl = "scene/reconnect";
					break;
				case "CSSceneDifficultyReq":
					serverUrl = "scene/getDifficulty";
					break;
				case "CSJigsawReconnectRequest":
					serverUrl = "jigsaw/reconnect";
					break;
				case "CSGetServiceConfigRequest":
					serverUrl = "sys/getServiceConfig";
					break;
				case "CSGetServiceConfigSingleRequest":
					serverUrl = "sys/getSingleServiceConfig";
					break;
				case "CSGetPathConfigRequest":
					serverUrl = "sys/path";
					break;
				case "CSClientLogRequest":
					serverUrl = "sys/clientLog";
					break;
				case "CSGetPushRequest":
					serverUrl = "push/getPush";
					break;
				case "CSBuyPushRequest":
					serverUrl = "push/buyPush";
					break;
				case "CSCombineInfoRequest":
					serverUrl = "combine/list";
					break;
				case "CSCombineRequest":
					serverUrl = "combine/do";
					break;
				default:
					break;
			}
			return serverUrl;
		}
	}
}
