//code generated by generator don't edit.
using Google.Protobuf;

namespace EngineCore
{
    public static class MessageDefine
	{
        public const int ExceptionResponse = 400;
        public const int ExceptionRemoteLoginResponse = 1;
        public const int GmAddAttr = 100;
        public const int GmAddProp = 101;
        public const int GmFinishTask = 102;
        public const int GmOfficer = 103;
        public const int GMGetPlayerMessageRequest = 106;
        public const int GMGetPlayerMessageResponse = 107;
        public const int CSEnterRequest = 1301;
        public const int SCEnterResponse = 1302;
        public const int CSQuitRequest = 1305;
        public const int SCQuitResponse = 1306;
        public const int CSSuspendRequest = 1307;
        public const int SCSuspendResponse = 1308;
        public const int CSResumeRequest = 1309;
        public const int SCResumeResponse = 1310;
        public const int CSStartRequest = 1311;
        public const int SCStartResponse = 1312;
        public const int CSFinishRequest = 1313;
        public const int SCFinishResponse = 1314;
        public const int CSRegRequest = 1001;
        public const int SCRegResponse = 1002;
        public const int CSAuthRequest = 1003;
        public const int SCAuthResponse = 1004;
        public const int CSloginRequest = 1007;
        public const int SCloginResponse = 1008;
        public const int CSChapterListRequest = 1011;
        public const int SCChapterListResponse = 1012;
        public const int CSChapterDetailRequest = 1013;
        public const int SCChapterDetailResponse = 1014;
        public const int SCClueUnlockNotice = 1019;
        public const int SCNpcUnLockNotice = 1020;
        public const int SCSceneUnLockNotice = 1021;
        public const int SCChapterTaskStatusChangeNotice = 1022;
        public const int SCChapterStatusChangeNotice = 1023;
        public const int SCChapterRedNotice = 1024;
        public const int CSClearChapterRedRequest = 1025;
        public const int CSSceneEnterRequest = 1101;
        public const int SCSceneEnterResponse = 1102;
        public const int CSSceneRewardRequest = 1103;
        public const int SCSceneRewardResponse = 1104;
        public const int CSSceneQuitRequest = 1105;
        public const int SCSceneQuitResponse = 1106;
        public const int CSSceneSuspendRequest = 1107;
        public const int SCSceneSuspendResponse = 1108;
        public const int CSSceneResumeRequest = 1109;
        public const int SCSceneResumeResponse = 1110;
        public const int CSSceneStartRequest = 1111;
        public const int SCSceneStartResponse = 1112;
        public const int CSSearchSceneSelectOfficerReq = 1113;
        public const int SCSearchSceneSelectOfficerResp = 1114;
        public const int CSBuyItemRequest = 1121;
        public const int SCBuyItemResponse = 1122;
        public const int CSPlayerPropRequest = 1201;
        public const int SCPlayerPropResponse = 1202;
        public const int CSPlayerPropRecentRequest = 1203;
        public const int SCPlayerPropRecentResposne = 1204;
        public const int CSPlayerInfoRequest = 1401;
        public const int SCPlayerInfoResponse = 1402;
        public const int CSRenameRequest = 1403;
        public const int SCRenameResponse = 1404;
        public const int CSOfficerListRequest = 1501;
        public const int SCOfficerListResponse = 1502;
        public const int CSOfficerInfoRequest = 1503;
        public const int SCOfficerInfoResponse = 1504;
        public const int CSEventPhaseFeedbackRequest = 1507;
        public const int SCEventPhaseFeedbackResponse = 1508;
        public const int CSEventRewardRequest = 1509;
        public const int SCEventRewardResponse = 1510;
        public const int CSOfficerCombineRequest = 1505;
        public const int SCOfficerCombineResponse = 1506;
        public const int CSOfficerUpdateRequest = 1511;
        public const int SCOfficerUpdateResponse = 1512;
        public const int CSEventEnterRequest = 1513;
        public const int SCEventEnterResponse = 1514;
        public const int CSEventDropInfoRequest = 1515;
        public const int SCEventDropInfoResponse = 1516;
        public const int CSSkillEmitRequest = 1601;
        public const int SCSkillEmitResponse = 1602;
        public const int CSSkillTimerEmitReq = 1603;
        public const int SCSkillTimerEmitResp = 1604;
        public const int CSReasoningRewardReq = 1605;
        public const int CSFindEnterReq = 1606;
        public const int SCFindEnterResp = 1607;
        public const int CSFindRewardReq = 1608;
        public const int SCFindRewardResp = 1609;
        public const int CSSkyEyeRewardReq = 1610;
        public const int SCSkyEyeRewardReq = 1611;
        public const int CSSkyEyeReq = 1612;
        public const int SCSkyEyeReq = 1613;
        public const int MarketRequest = 1701;
        public const int MarketResponse = 1702;
        public const int MarkeBuyRequest = 1703;
        public const int MarkeBuyResponse = 1704;
        public const int CSMarketItemRequest = 1711;
        public const int SCMarketItemResponse = 1712;
        public const int MarkeFreshRequest = 1705;
        public const int MarkeFreshResponse = 1706;
        public const int CSNoticeListRequest = 1801;
        public const int SCNoticeListResponse = 1802;
        public const int CSPingRequest = 1901;
        public const int SCPingResponse = 1902;
        public const int CSMessageRequest = 1903;
        public const int LottoRequest = 1707;
        public const int LottoResponse = 1708;
        public const int LottoBuyRequest = 1709;
        public const int LottoBuyResponse = 1710;
        public const int CSGooglePayChargeRequest = 1713;
        public const int SCGooglePayChargeResponse = 1714;
        public const int CSIOSPayChargeRequest = 1715;
        public const int SCIOSPayChargeResponse = 1716;
        public const int SCAcceptTaskNotice = 1820;
        public const int CSTaskListRequest = 1821;
        public const int SCTaskListResponse = 1822;
        public const int CSTaskCommitRequest = 1823;
        public const int SCTaskCommitResponse = 1824;
        public const int SCTaskStatusChangeNotice = 1825;
        public const int CSTriggerTaskActiveRequest = 1827;
        public const int SCTriggerTaskActiveResponse = 1828;
        public const int CSTaskIdListRequest = 1841;
        public const int SCTaskIdListResponse = 1842;
        public const int CSAchievementRequest = 1829;
        public const int SCAchievementResponse = 1830;
        public const int CSAchievementSubmitRequest = 1831;
        public const int SCAchievementSubmitResponse = 1832;
        public const int CSActivityBaseListRequest = 2021;
        public const int SCActivityBaseListResponse = 2022;
        public const int CSActivityRequest = 2024;
        public const int SCActivityDropResponse = 2025;
        public const int CSActivityRewardRequest = 2026;
        public const int SCActivityRewardResponse = 2027;
        public const int CSCartoonEnterRequest = 2101;
        public const int SCCartoonEnterResponse = 2102;
        public const int CSCartoonRewardRequest = 2103;
        public const int SCCartoonRewardReqsponse = 2104;
        public const int CSCartoonQuitRequest = 2105;
        public const int CSEmailListRequest = 2201;
        public const int SCEmailListResponse = 2202;
        public const int CSEmailRewardRequest = 2203;
        public const int SCEmailRewardResponse = 2204;
        public const int CSEmailReadRequest = 2205;
        public const int SCEmailChangeNotice = 2207;
        public const int CSTitleRequest = 1833;
        public const int SCTitleResponse = 1834;
        public const int CSTitleActiveRequest = 1835;
        public const int SCTitleActiveResponse = 1836;
        public const int CSTitleGetRequest = 1837;
        public const int SCTitleGetResponse = 1838;
        public const int CSFriendRequest = 2301;
        public const int SCFriendResponse = 2302;
        public const int CSFriendAddRequest = 2303;
        public const int SCFriendAddResponse = 2304;
        public const int CSFriendDelRequest = 2305;
        public const int SCFriendDelResponse = 2306;
        public const int CSFriendAgreeRequest = 2307;
        public const int SCFriendAgreeResponse = 2308;
        public const int CSFriendDelApplyRequest = 2309;
        public const int SCFriendDelApplyResponse = 2310;
        public const int CSFriendGiftRequest = 2311;
        public const int SCFriendGiftResponse = 2312;
        public const int CSFriendGiftSendRequest = 2313;
        public const int SCFriendGiftSendResponse = 2314;
        public const int CSFriendGiftDrawRequest = 2316;
        public const int SCFriendGiftDrawResponse = 2317;
        public const int CSFriendViewRequest = 2318;
        public const int SCFriendViewResponse = 2319;
        public const int CSFriendSwitchRequest = 2320;
        public const int SCFriendSwitchResponse = 2321;
        public const int SCFriendApplyResponse = 2323;
        public const int SCFriendNoticeResponse = 2324;
        public const int CSFriendRecommendListRequest = 2325;
        public const int SCFriendRecommendListResponse = 2326;
        public const int CSFriendRecommendGetRequest = 2327;
        public const int SCFriendRecommendGetResponse = 2328;
        public const int CSFriendRecommendApplyRequest = 2329;
        public const int SCFriendRecommendApplyResponse = 2330;
        public const int CSBuildingListReq = 2401;
        public const int SCBuildingListResp = 2402;
        public const int CSBuildingUnlockReq = 2403;
        public const int SCBuildingUnlockResp = 2404;
        public const int CSCanTaskRequest = 1848;
        public const int SCCanTaskResponse = 1849;
        public const int SCreceiveNewTitle = 1850;
        public const int CSRegGuestRequest = 1040;
        public const int SCRegGuestResponse = 1041;
        public const int CSIdentifyCheckRequest = 1044;
        public const int SCIdentifyCheckRepsonse = 1045;
        public const int CSFBLoginRequest = 1046;
        public const int SCFBLoginResponse = 1047;
        public const int CSFBBindRequest = 1048;
        public const int SCFBBindResponse = 1049;
        public const int SCIdentifyCheckMuiltyMessage = 1050;
        public const int PlayerPropSellRequest = 1207;
        public const int PlayerPropSellResposne = 1208;
        public const int CSDropReq = 1209;
        public const int SCDropResp = 1210;
        public const int SCAutoOpenGiftDropResp = 1211;
        public const int CSChatFinishRequest = 1843;
        public const int SCChatFinishResponse = 1844;
        public const int CSGetAllRewardedTasksRequest = 1845;
        public const int SCGetAllRewardedTasksResponse = 1846;
        public const int CSPlayerCheckInInfoReq = 1405;
        public const int SCPlayerCheckInInfoResp = 1406;
        public const int CSPlayerCheckInReq = 1407;
        public const int SCPlayerCheckInResp = 1408;
        public const int CSPlayerRenewIconReq = 1409;
        public const int SCPlayerRenewIconResp = 1410;
        public const int SCPlayerUpLevel = 1411;
        public const int CSPlayerGuildRequest = 1412;
        public const int SCPlayerGuildResponse = 1413;
        public const int CSPlayerGuildUpdateRequest = 1414;
        public const int CSPlayerFeedbackRequest = 2500;
        public const int SCPlayerFeedbackResponse = 2501;
        public const int SCAchievementUnlockResponse = 1847;
        public const int SCActivityNewResponse = 2023;
        public const int CSSceneReconnectRequest = 1115;
        public const int SCSceneReconnectResponse = 1116;
        public const int CSSceneDifficultyReq = 1117;
        public const int SCSceneDifficultyResp = 1118;
        public const int CSJigsawReconnectRequest = 1315;
        public const int SCJigsawReconnectResponse = 1316;
        public const int CSGetServiceConfigRequest = 2331;
        public const int SCGetServiceConfigResponse = 2332;
        public const int CSGetServiceConfigSingleRequest = 2333;
        public const int SCGetServiceConfigSingleResponse = 2334;
        public const int CSGetPathConfigRequest = 2335;
        public const int SCGetPathConfigResponse = 2336;
        public const int CSClientLogRequest = 2337;
        public const int CSGetPushRequest = 2801;
        public const int SCGetPushResponse = 2802;
        public const int CSBuyPushRequest = 2803;
        public const int SCBuyPushResponse = 2804;
        public const int CSCombineInfoRequest = 1517;
        public const int SCCombineInfoResponse = 1518;
        public const int CSCombineRequest = 1519;
        public const int SCCombineResponse = 1520;

        public static int GetMessageId(this IMessage message)
        {
        	int messageId = 0;
        	switch (message.Descriptor.Name)
        	{
        		case "ExceptionResponse":
        			messageId = 400;
        			break;
        		case "ExceptionRemoteLoginResponse":
        			messageId = 1;
        			break;
        		case "GmAddAttr":
        			messageId = 100;
        			break;
        		case "GmAddProp":
        			messageId = 101;
        			break;
        		case "GmFinishTask":
        			messageId = 102;
        			break;
        		case "GmOfficer":
        			messageId = 103;
        			break;
        		case "GMGetPlayerMessageRequest":
        			messageId = 106;
        			break;
        		case "GMGetPlayerMessageResponse":
        			messageId = 107;
        			break;
        		case "CSEnterRequest":
        			messageId = 1301;
        			break;
        		case "SCEnterResponse":
        			messageId = 1302;
        			break;
        		case "CSQuitRequest":
        			messageId = 1305;
        			break;
        		case "SCQuitResponse":
        			messageId = 1306;
        			break;
        		case "CSSuspendRequest":
        			messageId = 1307;
        			break;
        		case "SCSuspendResponse":
        			messageId = 1308;
        			break;
        		case "CSResumeRequest":
        			messageId = 1309;
        			break;
        		case "SCResumeResponse":
        			messageId = 1310;
        			break;
        		case "CSStartRequest":
        			messageId = 1311;
        			break;
        		case "SCStartResponse":
        			messageId = 1312;
        			break;
        		case "CSFinishRequest":
        			messageId = 1313;
        			break;
        		case "SCFinishResponse":
        			messageId = 1314;
        			break;
        		case "CSRegRequest":
        			messageId = 1001;
        			break;
        		case "SCRegResponse":
        			messageId = 1002;
        			break;
        		case "CSAuthRequest":
        			messageId = 1003;
        			break;
        		case "SCAuthResponse":
        			messageId = 1004;
        			break;
        		case "CSloginRequest":
        			messageId = 1007;
        			break;
        		case "SCloginResponse":
        			messageId = 1008;
        			break;
        		case "CSChapterListRequest":
        			messageId = 1011;
        			break;
        		case "SCChapterListResponse":
        			messageId = 1012;
        			break;
        		case "CSChapterDetailRequest":
        			messageId = 1013;
        			break;
        		case "SCChapterDetailResponse":
        			messageId = 1014;
        			break;
        		case "SCClueUnlockNotice":
        			messageId = 1019;
        			break;
        		case "SCNpcUnLockNotice":
        			messageId = 1020;
        			break;
        		case "SCSceneUnLockNotice":
        			messageId = 1021;
        			break;
        		case "SCChapterTaskStatusChangeNotice":
        			messageId = 1022;
        			break;
        		case "SCChapterStatusChangeNotice":
        			messageId = 1023;
        			break;
        		case "SCChapterRedNotice":
        			messageId = 1024;
        			break;
        		case "CSClearChapterRedRequest":
        			messageId = 1025;
        			break;
        		case "CSSceneEnterRequest":
        			messageId = 1101;
        			break;
        		case "SCSceneEnterResponse":
        			messageId = 1102;
        			break;
        		case "CSSceneRewardRequest":
        			messageId = 1103;
        			break;
        		case "SCSceneRewardResponse":
        			messageId = 1104;
        			break;
        		case "CSSceneQuitRequest":
        			messageId = 1105;
        			break;
        		case "SCSceneQuitResponse":
        			messageId = 1106;
        			break;
        		case "CSSceneSuspendRequest":
        			messageId = 1107;
        			break;
        		case "SCSceneSuspendResponse":
        			messageId = 1108;
        			break;
        		case "CSSceneResumeRequest":
        			messageId = 1109;
        			break;
        		case "SCSceneResumeResponse":
        			messageId = 1110;
        			break;
        		case "CSSceneStartRequest":
        			messageId = 1111;
        			break;
        		case "SCSceneStartResponse":
        			messageId = 1112;
        			break;
        		case "CSSearchSceneSelectOfficerReq":
        			messageId = 1113;
        			break;
        		case "SCSearchSceneSelectOfficerResp":
        			messageId = 1114;
        			break;
        		case "CSBuyItemRequest":
        			messageId = 1121;
        			break;
        		case "SCBuyItemResponse":
        			messageId = 1122;
        			break;
        		case "CSPlayerPropRequest":
        			messageId = 1201;
        			break;
        		case "SCPlayerPropResponse":
        			messageId = 1202;
        			break;
        		case "CSPlayerPropRecentRequest":
        			messageId = 1203;
        			break;
        		case "SCPlayerPropRecentResposne":
        			messageId = 1204;
        			break;
        		case "CSPlayerInfoRequest":
        			messageId = 1401;
        			break;
        		case "SCPlayerInfoResponse":
        			messageId = 1402;
        			break;
        		case "CSRenameRequest":
        			messageId = 1403;
        			break;
        		case "SCRenameResponse":
        			messageId = 1404;
        			break;
        		case "CSOfficerListRequest":
        			messageId = 1501;
        			break;
        		case "SCOfficerListResponse":
        			messageId = 1502;
        			break;
        		case "CSOfficerInfoRequest":
        			messageId = 1503;
        			break;
        		case "SCOfficerInfoResponse":
        			messageId = 1504;
        			break;
        		case "CSEventPhaseFeedbackRequest":
        			messageId = 1507;
        			break;
        		case "SCEventPhaseFeedbackResponse":
        			messageId = 1508;
        			break;
        		case "CSEventRewardRequest":
        			messageId = 1509;
        			break;
        		case "SCEventRewardResponse":
        			messageId = 1510;
        			break;
        		case "CSOfficerCombineRequest":
        			messageId = 1505;
        			break;
        		case "SCOfficerCombineResponse":
        			messageId = 1506;
        			break;
        		case "CSOfficerUpdateRequest":
        			messageId = 1511;
        			break;
        		case "SCOfficerUpdateResponse":
        			messageId = 1512;
        			break;
        		case "CSEventEnterRequest":
        			messageId = 1513;
        			break;
        		case "SCEventEnterResponse":
        			messageId = 1514;
        			break;
        		case "CSEventDropInfoRequest":
        			messageId = 1515;
        			break;
        		case "SCEventDropInfoResponse":
        			messageId = 1516;
        			break;
        		case "CSSkillEmitRequest":
        			messageId = 1601;
        			break;
        		case "SCSkillEmitResponse":
        			messageId = 1602;
        			break;
        		case "CSSkillTimerEmitReq":
        			messageId = 1603;
        			break;
        		case "SCSkillTimerEmitResp":
        			messageId = 1604;
        			break;
        		case "CSReasoningRewardReq":
        			messageId = 1605;
        			break;
        		case "CSFindEnterReq":
        			messageId = 1606;
        			break;
        		case "SCFindEnterResp":
        			messageId = 1607;
        			break;
        		case "CSFindRewardReq":
        			messageId = 1608;
        			break;
        		case "SCFindRewardResp":
        			messageId = 1609;
        			break;
        		case "CSSkyEyeRewardReq":
        			messageId = 1610;
        			break;
        		case "SCSkyEyeRewardReq":
        			messageId = 1611;
        			break;
        		case "CSSkyEyeReq":
        			messageId = 1612;
        			break;
        		case "SCSkyEyeReq":
        			messageId = 1613;
        			break;
        		case "MarketRequest":
        			messageId = 1701;
        			break;
        		case "MarketResponse":
        			messageId = 1702;
        			break;
        		case "MarkeBuyRequest":
        			messageId = 1703;
        			break;
        		case "MarkeBuyResponse":
        			messageId = 1704;
        			break;
        		case "CSMarketItemRequest":
        			messageId = 1711;
        			break;
        		case "SCMarketItemResponse":
        			messageId = 1712;
        			break;
        		case "MarkeFreshRequest":
        			messageId = 1705;
        			break;
        		case "MarkeFreshResponse":
        			messageId = 1706;
        			break;
        		case "CSNoticeListRequest":
        			messageId = 1801;
        			break;
        		case "SCNoticeListResponse":
        			messageId = 1802;
        			break;
        		case "CSPingRequest":
        			messageId = 1901;
        			break;
        		case "SCPingResponse":
        			messageId = 1902;
        			break;
        		case "CSMessageRequest":
        			messageId = 1903;
        			break;
        		case "LottoRequest":
        			messageId = 1707;
        			break;
        		case "LottoResponse":
        			messageId = 1708;
        			break;
        		case "LottoBuyRequest":
        			messageId = 1709;
        			break;
        		case "LottoBuyResponse":
        			messageId = 1710;
        			break;
        		case "CSGooglePayChargeRequest":
        			messageId = 1713;
        			break;
        		case "SCGooglePayChargeResponse":
        			messageId = 1714;
        			break;
        		case "CSIOSPayChargeRequest":
        			messageId = 1715;
        			break;
        		case "SCIOSPayChargeResponse":
        			messageId = 1716;
        			break;
        		case "SCAcceptTaskNotice":
        			messageId = 1820;
        			break;
        		case "CSTaskListRequest":
        			messageId = 1821;
        			break;
        		case "SCTaskListResponse":
        			messageId = 1822;
        			break;
        		case "CSTaskCommitRequest":
        			messageId = 1823;
        			break;
        		case "SCTaskCommitResponse":
        			messageId = 1824;
        			break;
        		case "SCTaskStatusChangeNotice":
        			messageId = 1825;
        			break;
        		case "CSTriggerTaskActiveRequest":
        			messageId = 1827;
        			break;
        		case "SCTriggerTaskActiveResponse":
        			messageId = 1828;
        			break;
        		case "CSTaskIdListRequest":
        			messageId = 1841;
        			break;
        		case "SCTaskIdListResponse":
        			messageId = 1842;
        			break;
        		case "CSAchievementRequest":
        			messageId = 1829;
        			break;
        		case "SCAchievementResponse":
        			messageId = 1830;
        			break;
        		case "CSAchievementSubmitRequest":
        			messageId = 1831;
        			break;
        		case "SCAchievementSubmitResponse":
        			messageId = 1832;
        			break;
        		case "CSActivityBaseListRequest":
        			messageId = 2021;
        			break;
        		case "SCActivityBaseListResponse":
        			messageId = 2022;
        			break;
        		case "CSActivityRequest":
        			messageId = 2024;
        			break;
        		case "SCActivityDropResponse":
        			messageId = 2025;
        			break;
        		case "CSActivityRewardRequest":
        			messageId = 2026;
        			break;
        		case "SCActivityRewardResponse":
        			messageId = 2027;
        			break;
        		case "CSCartoonEnterRequest":
        			messageId = 2101;
        			break;
        		case "SCCartoonEnterResponse":
        			messageId = 2102;
        			break;
        		case "CSCartoonRewardRequest":
        			messageId = 2103;
        			break;
        		case "SCCartoonRewardReqsponse":
        			messageId = 2104;
        			break;
        		case "CSCartoonQuitRequest":
        			messageId = 2105;
        			break;
        		case "CSEmailListRequest":
        			messageId = 2201;
        			break;
        		case "SCEmailListResponse":
        			messageId = 2202;
        			break;
        		case "CSEmailRewardRequest":
        			messageId = 2203;
        			break;
        		case "SCEmailRewardResponse":
        			messageId = 2204;
        			break;
        		case "CSEmailReadRequest":
        			messageId = 2205;
        			break;
        		case "SCEmailChangeNotice":
        			messageId = 2207;
        			break;
        		case "CSTitleRequest":
        			messageId = 1833;
        			break;
        		case "SCTitleResponse":
        			messageId = 1834;
        			break;
        		case "CSTitleActiveRequest":
        			messageId = 1835;
        			break;
        		case "SCTitleActiveResponse":
        			messageId = 1836;
        			break;
        		case "CSTitleGetRequest":
        			messageId = 1837;
        			break;
        		case "SCTitleGetResponse":
        			messageId = 1838;
        			break;
        		case "CSFriendRequest":
        			messageId = 2301;
        			break;
        		case "SCFriendResponse":
        			messageId = 2302;
        			break;
        		case "CSFriendAddRequest":
        			messageId = 2303;
        			break;
        		case "SCFriendAddResponse":
        			messageId = 2304;
        			break;
        		case "CSFriendDelRequest":
        			messageId = 2305;
        			break;
        		case "SCFriendDelResponse":
        			messageId = 2306;
        			break;
        		case "CSFriendAgreeRequest":
        			messageId = 2307;
        			break;
        		case "SCFriendAgreeResponse":
        			messageId = 2308;
        			break;
        		case "CSFriendDelApplyRequest":
        			messageId = 2309;
        			break;
        		case "SCFriendDelApplyResponse":
        			messageId = 2310;
        			break;
        		case "CSFriendGiftRequest":
        			messageId = 2311;
        			break;
        		case "SCFriendGiftResponse":
        			messageId = 2312;
        			break;
        		case "CSFriendGiftSendRequest":
        			messageId = 2313;
        			break;
        		case "SCFriendGiftSendResponse":
        			messageId = 2314;
        			break;
        		case "CSFriendGiftDrawRequest":
        			messageId = 2316;
        			break;
        		case "SCFriendGiftDrawResponse":
        			messageId = 2317;
        			break;
        		case "CSFriendViewRequest":
        			messageId = 2318;
        			break;
        		case "SCFriendViewResponse":
        			messageId = 2319;
        			break;
        		case "CSFriendSwitchRequest":
        			messageId = 2320;
        			break;
        		case "SCFriendSwitchResponse":
        			messageId = 2321;
        			break;
        		case "SCFriendApplyResponse":
        			messageId = 2323;
        			break;
        		case "SCFriendNoticeResponse":
        			messageId = 2324;
        			break;
        		case "CSFriendRecommendListRequest":
        			messageId = 2325;
        			break;
        		case "SCFriendRecommendListResponse":
        			messageId = 2326;
        			break;
        		case "CSFriendRecommendGetRequest":
        			messageId = 2327;
        			break;
        		case "SCFriendRecommendGetResponse":
        			messageId = 2328;
        			break;
        		case "CSFriendRecommendApplyRequest":
        			messageId = 2329;
        			break;
        		case "SCFriendRecommendApplyResponse":
        			messageId = 2330;
        			break;
        		case "CSBuildingListReq":
        			messageId = 2401;
        			break;
        		case "SCBuildingListResp":
        			messageId = 2402;
        			break;
        		case "CSBuildingUnlockReq":
        			messageId = 2403;
        			break;
        		case "SCBuildingUnlockResp":
        			messageId = 2404;
        			break;
        		case "CSCanTaskRequest":
        			messageId = 1848;
        			break;
        		case "SCCanTaskResponse":
        			messageId = 1849;
        			break;
        		case "SCreceiveNewTitle":
        			messageId = 1850;
        			break;
        		case "CSRegGuestRequest":
        			messageId = 1040;
        			break;
        		case "SCRegGuestResponse":
        			messageId = 1041;
        			break;
        		case "CSIdentifyCheckRequest":
        			messageId = 1044;
        			break;
        		case "SCIdentifyCheckRepsonse":
        			messageId = 1045;
        			break;
        		case "CSFBLoginRequest":
        			messageId = 1046;
        			break;
        		case "SCFBLoginResponse":
        			messageId = 1047;
        			break;
        		case "CSFBBindRequest":
        			messageId = 1048;
        			break;
        		case "SCFBBindResponse":
        			messageId = 1049;
        			break;
        		case "SCIdentifyCheckMuiltyMessage":
        			messageId = 1050;
        			break;
        		case "PlayerPropSellRequest":
        			messageId = 1207;
        			break;
        		case "PlayerPropSellResposne":
        			messageId = 1208;
        			break;
        		case "CSDropReq":
        			messageId = 1209;
        			break;
        		case "SCDropResp":
        			messageId = 1210;
        			break;
        		case "SCAutoOpenGiftDropResp":
        			messageId = 1211;
        			break;
        		case "CSChatFinishRequest":
        			messageId = 1843;
        			break;
        		case "SCChatFinishResponse":
        			messageId = 1844;
        			break;
        		case "CSGetAllRewardedTasksRequest":
        			messageId = 1845;
        			break;
        		case "SCGetAllRewardedTasksResponse":
        			messageId = 1846;
        			break;
        		case "CSPlayerCheckInInfoReq":
        			messageId = 1405;
        			break;
        		case "SCPlayerCheckInInfoResp":
        			messageId = 1406;
        			break;
        		case "CSPlayerCheckInReq":
        			messageId = 1407;
        			break;
        		case "SCPlayerCheckInResp":
        			messageId = 1408;
        			break;
        		case "CSPlayerRenewIconReq":
        			messageId = 1409;
        			break;
        		case "SCPlayerRenewIconResp":
        			messageId = 1410;
        			break;
        		case "SCPlayerUpLevel":
        			messageId = 1411;
        			break;
        		case "CSPlayerGuildRequest":
        			messageId = 1412;
        			break;
        		case "SCPlayerGuildResponse":
        			messageId = 1413;
        			break;
        		case "CSPlayerGuildUpdateRequest":
        			messageId = 1414;
        			break;
        		case "CSPlayerFeedbackRequest":
        			messageId = 2500;
        			break;
        		case "SCPlayerFeedbackResponse":
        			messageId = 2501;
        			break;
        		case "SCAchievementUnlockResponse":
        			messageId = 1847;
        			break;
        		case "SCActivityNewResponse":
        			messageId = 2023;
        			break;
        		case "CSSceneReconnectRequest":
        			messageId = 1115;
        			break;
        		case "SCSceneReconnectResponse":
        			messageId = 1116;
        			break;
        		case "CSSceneDifficultyReq":
        			messageId = 1117;
        			break;
        		case "SCSceneDifficultyResp":
        			messageId = 1118;
        			break;
        		case "CSJigsawReconnectRequest":
        			messageId = 1315;
        			break;
        		case "SCJigsawReconnectResponse":
        			messageId = 1316;
        			break;
        		case "CSGetServiceConfigRequest":
        			messageId = 2331;
        			break;
        		case "SCGetServiceConfigResponse":
        			messageId = 2332;
        			break;
        		case "CSGetServiceConfigSingleRequest":
        			messageId = 2333;
        			break;
        		case "SCGetServiceConfigSingleResponse":
        			messageId = 2334;
        			break;
        		case "CSGetPathConfigRequest":
        			messageId = 2335;
        			break;
        		case "SCGetPathConfigResponse":
        			messageId = 2336;
        			break;
        		case "CSClientLogRequest":
        			messageId = 2337;
        			break;
        		case "CSGetPushRequest":
        			messageId = 2801;
        			break;
        		case "SCGetPushResponse":
        			messageId = 2802;
        			break;
        		case "CSBuyPushRequest":
        			messageId = 2803;
        			break;
        		case "SCBuyPushResponse":
        			messageId = 2804;
        			break;
        		case "CSCombineInfoRequest":
        			messageId = 1517;
        			break;
        		case "SCCombineInfoResponse":
        			messageId = 1518;
        			break;
        		case "CSCombineRequest":
        			messageId = 1519;
        			break;
        		case "SCCombineResponse":
        			messageId = 1520;
        			break;
        		default:
        			break;
        	}

        	return messageId;
    	}
    }
}
