// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from options.proto</summary>
public static partial class OptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for options.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1vcHRpb25zLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5w",
          "cm90bzo3CgxzZXJ2ZXJUYXJnZXQSHy5nb29nbGUucHJvdG9idWYuTWVzc2Fn",
          "ZU9wdGlvbnMYopADIAEoCTo0CgltZXNzYWdlSWQSHy5nb29nbGUucHJvdG9i",
          "dWYuTWVzc2FnZU9wdGlvbnMYo5ADIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
        new pbr::GeneratedClrTypeInfo(null, null));
  }
  #endregion

}

#endregion Designer generated code
